
trigger:
- develop
- test

pool:
  name: 'maquina-test' # O el nombre del pool donde está tu agente on-premise

steps:
# 1. Descargar el código limpio en la carpeta de trabajo del agente
- checkout: self
  clean: true

# 2. Apagar la versión anterior de test (si es que ya estaba corriendo)
- script: |
    docker compose -f docker-compose.test.yml down
  displayName: 'Deteniendo contenedor de pruebas anterior'
  continueOnError: true # Si es la primera vez y no existe, no romperá el pipeline

# 3. Compilar la nueva versión de Docker directamente en tu servidor
- script: |
    docker compose -f docker-compose.test.yml build --no-cache
  displayName: 'Compilando nueva imagen de Docker en Local (Test)'

# 4. Encender el nuevo contenedor en segundo plano (-d)
- script: |
    docker compose -f docker-compose.test.yml up -d
  displayName: 'Desplegando nuevo contenedor en ambiente de Test'

# 5. Limpieza para que el disco del servidor no se llene con imágenes viejas
- script: |
    docker image prune -f
  displayName: 'Limpiando imágenes Docker huérfanas'